### PR TITLE
fix #37

### LINKED ISSUE #37: get-pip no longer works with explicit args for pip
Hi!

Try `curl https://bootstrap.pypa.io/get-pip.py | python - pip==18.0` and you will see that a `DoubleRequirement` exception is thrown. If you debug a bit, you'll find that actually `InstallRequirement.from_line` fails (`InstallRequirement` does not have `from_line`) and that triggers the `continue` call in the loop.

Thanks!

### PR DESCRIPTION
**Pull request by benoit-pierre**

### CODE REVIEW

**Comment by cloneluke** [comment]
+1 for this fix asap

**Comment by forslund** [comment]
I gave it a try on Ubuntu 18.04 and is working nicely.

**Comment by benoit-pierre** [comment]
Updated the templates too.

**Comment by cloneluke** [comment]
another workaround is hard code the get-pip URL to prior version:

https://raw.githubusercontent.com/pypa/get-pip/f88ab195ecdf2f0001ed21443e247fb32265cabb/get-pip.py

**Comment by rbreslow** [comment]
@cloneluke you can also do https://bootstrap.pypa.io/3.3/get-pip.py

**Pull request merged**
