### PR TITLE
The PyPA has adopted the PSF code of conduct

### PR DESCRIPTION
**Pull request by hugovk**
For details, see:

* https://discuss.python.org/t/implementing-pep-609-pypa-governance/4745

### CODE REVIEW

**Comment by pradyunsg** [comment]
#68 covers this?

**Comment by hugovk** [comment]
Oh yes, sorry!

I just posted on the [discuss.python.org thread](https://discuss.python.org/t/implementing-pep-609-pypa-governance/4745/5?u=hugovk): which link do you think's better?

**Comment by pradyunsg** [comment]
I think #68, because it skips needing to click through an extra link to get to the relevant reporting details. :)

**Comment by hugovk** [comment]
Sounds good, will go for that with the other repos.

**Comment by pradyunsg** [comment]
Thank you @hugovk! ^.^

**Pull request closed without merging**
