### PR TITLE
Generate versioned zipapps for all supported pip versions

### PR DESCRIPTION
**Pull request by pfmoore**
This needs tidying up, but initially it seems to work. Publishing in this form mainly as a checkpoint.

### CODE REVIEW

**Comment by pfmoore** [comment]
OK, that's better. I think this is ready to go.

**Comment by pfmoore** [comment]
@pradyunsg gentle ping on this. I noticed we still aren't doing this while doing the 23.2.1 release...

**Comment by NickDeClario** [comment]
This is an excellent feature that I'd love to see in.  I was wondering if there was any movement on this or further discussion?

**Review by pradyunsg — APPROVED** [review]

**Comment by pradyunsg** [comment]
@pfmoore Before merging this, could you please regenerate the scripts here?

**Pull request merged**
