### PR TITLE
Run flake8 via pre-commit

### PR DESCRIPTION
**Pull request by peternewman**
This is currently deliberately running without #77 in place to test and show the failing output.

### CODE REVIEW

**Comment by pradyunsg** [comment]
I don't think we need the annotation, or that we need to run pre-commit twice. Just once is enough.

**Comment by peternewman** [comment]
> I don't think we need the annotation,

Okay, I can remove it if you want, I think it's quite a nice feature personally and I've been trying to put it into any actions I use to make things more user-friendly for people.

> or that we need to run pre-commit twice. Just once is enough.

Running flake8 as Python 2 and Python 3 will both produce different results. Given you're still targeting both, I think if it's only run once it will potentially miss some issues.

**Comment by pradyunsg** [comment]
> Given you're still targeting both, I think if it's only run once it will potentially miss some issues.

We've documented that we're dropping support for Python 2 this month in pip 21.0, and I'd rather we don't create busy work to do next week. :)

**Comment by peternewman** [comment]
> We've documented that we're dropping support for Python 2 this month in pip 21.0, and I'd rather we don't create busy work to do next week. :)

Ah sorry, I'd not seen that. I've now removed that bit from the config.

**Comment by pradyunsg** [comment]
Closing since this is significantly out of date and the whole automation has been rewritten in #85.

I still feel that there is very little value to linting the code in this repository via CI -- and it is basically useless for the generated scripts. It's likely fine to not do this, and any energy we put into updating this is probably better spent removing lines from https://github.com/pypa/pip/blob/master/.pre-commit-config.yaml#L23 (one by one in separate PRs, so that it's easier to review those PRs).

Thanks for working on this though @peternewman! Much appreciated! ^>^

**Pull request closed without merging**
