### PR TITLE
[WIP] Add a very basic test suite

### PR DESCRIPTION
**Pull request by pfmoore**

### CODE REVIEW

**Comment by webknjaz** [comment]
I feel like this thing might be a good choice for testing script execution: https://pypi.org/project/pytest-console-scripts/

**Comment by hugovk** [comment]
Compared with #23, this sort of approach does look more portable between Python versions (eg. with Tox) and also between operating systems. 

CI would be great to ensure things keep ticking over smoothly. It's also an easy way to run the tests cleanly on different versions and operating systems without needing to worry about covering it all locally, finding machines.

**Comment by pfmoore** [comment]
pytest-console-scripts and tox aren't really relevant here, as this projects isn't an installable Python package... Also, for context - this project has only had 35 commits in its whole lifetime. Investing in CI, code style checks, etc, could be over-engineering things. All I personally care about is having a way of standardising the final "please tell me I didn't break the build" step.

**Comment by pradyunsg** [comment]
I'll take a stab at this now, given the recent breakage - #37.

I think I'll skip the CI and code style checks since they're not really relevant to the workflow IMO. I do think having a way to check across multiple Python versions via tox perhaps, _might_ be useful.

**Comment by pradyunsg** [comment]
Superceded by #85, so I'll close this.

**Pull request closed without merging**
