### PR TITLE
Add Python 3.5 compatible get-pip.py

### PR DESCRIPTION
**Pull request by pradyunsg**
This isn't sufficient on it's own -- we'd also need to update psf-salt for this.

### CODE REVIEW

**Comment by pfmoore** [comment]
Thanks for catching this, @pradyunsg - with the focus on dropping 2.7, I'd missed that we were also dropping 3.5 support.

@ewdurbin if you can make the salt changes (again!) that would be great.

**Comment by pfmoore** [comment]
I wonder if we'd be better with a file structure that put the legacy versions under our control:

```
+- pip
   +- get-pip.py
   +- 2.6
       +- get-pip.py
   +- 2.7
       +- get-pip.py
   ... (etc)
```

We'd obviously need to make links for the existing names, but future names could *just* sit under `pip` and not need changes to the salt config?

**Comment by pradyunsg** [comment]
Yup. That's what #61 is all about. :)

**Pull request merged**
